name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      enviornment:
        description: "Select Deployment Enviornment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      app_version:
        description: "Application Version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Show Deployment Details
        run: |
          echo "Environment: ${{ github.event.inputs.enviornment }}"
          echo "Version: ${{ github.event.inputs.app_version }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          echo "Deployment completed"
        
        
    
